# label rules used by .github/workflows/label.yml

# label 'ci' all automation-related steps and files
#   Since this repository is in itself an automation process to deploy a server instance,
#   we refer here to CI as the 'meta' configuration files for managing the code and integrations with the repository,
#   not configurations related to the deployment process itself.
#
# idea from https://github.com/Ouranosinc/xclim/blob/main/.github/labeler.yml

'CI':
  - changed-files:
    - any-glob-to-any-file:
      - '.editorconfig'
      - '.flake8'
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - '.readthedocs.yaml'
      - '.yamllint.yaml'
      - '.github/workflows/*'
      - 'docs/Makefile'
      - 'tox.toml'
      - 'CI/**/*'
      - 'Makefile'

'docs':
  - changed-files:
    - any-glob-to-any-file:
      - '.readthedocs.yml'
      - 'docs/**/*'
      - 'environment-docs.yml'
      - 'AUTHORS.rst'
      - 'CONTRIBUTING.rst'
      - 'CODE_OF_CONDUCT.md'
      - 'DISCUSSION_TEMPLATE/**/*'
      - 'ISSUE_TEMPLATE/**/*'
      - 'ISSUE_TEMPLATE.md'
      - 'PULL_REQUEST_TEMPLATE.md'
      - 'README.rst'
      - 'CHANGELOG.rst'

'cdm_mapper':
  - changed-files:
    - any-glob-to-any-file:
      - 'src/cdm_reader_mapper/cdm_mapper/*.py'
      - 'src/cdm_reader_mapper/cdm_mapper/**/*.py'
      - 'src/cdm_reader_mapper/cdm_mapper/codes/**/*.json'
      - 'src/cdm_reader_mapper/cdm_mapper/tables/**/*.json'

'common':
  - changed-files:
    - any-glob-to-any-file:
      - 'src/cdm_reader_mapper/common/*.py'

'mdf_reader':
  - changed-files:
    - any-glob-to-any-file:
      - 'src/cdm_reader_mapper/mdf_reader/*.py'
      - 'src/cdm_reader_mapper/mdf_reader/**/*.py'
      - 'src/cdm_reader_mapper/mdf_reader/code_tables/**/*.json'
      - 'src/cdm_reader_mapper/mdf_reader/schema/**/*.json'
      - 'src/cdm_reader_mapper/mdf_reader/utils/*.py'

'metmetpy':
  - changed-files:
    - any-glob-to-any-file:
      - 'src/cdm_reader_mapper/metmetpy/properties.py'
      - 'src/cdm_reader_mapper/metmetpy/**/*.py'

'operations':
  - changed-files:
    - any-glob-to-any-file:
      - 'src/cdm_reader_mapper/operations/*.py'

'information':
  - changed-files:
    - any-glob-to-any-file:
      - 'CONTRIBUTING.rst'
      - 'CHANGELOG.rst'

'license':
  - changed-files:
    - any-glob-to-any-file:
      - 'LICENSE'

'zenodo':
  - changed-files:
    - any-glob-to-any-file:
      - '.zenodo.json'

'release':
  - changed-files:
    - any-glob-to-any-file:
      - 'pyproject.toml'

'testing suite':
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**/*'
      - 'tests/*'
