diff a/Makefile b/Makefile	(rejected hunks)
@@ -100,7 +100,7 @@ ifndef READTHEDOCS
 endif
 
 servedocs: autodoc ## compile the docs while watching for changes
-	watchmedo shell-command -p '*.rst' -c '$(MAKE) -C docs html' -R -D .
+	$(MAKE) -C docs livehtml
 
 dist: clean ## builds source and wheel package
 	python -m flit build
