name: cdm-test

channels:
    - conda-forge
    - nodefaults

dependencies:
    - pandas
    - dask
    - matplotlib
    - xarray
    - bottleneck
    - netcdf4
    - h5netcdf
    - datashader
    - pyarrow
    # https://github.com/openforcefield/openff-nagl/issues/106
    # for testing
    - pytest
    - pytest-cov
    - pytest-env
    #from pypi
    - pip:
      - msgpack
      - requests
      - timezonefinder
      - python-slugify
      - textdistance
      - swifter
      - platformdirs
      - recordlinkage
